quarkus.http.port=8080

graphviz.dir=/usr/bin
cache.dir=/tmp/vcat
vcat.threads=4

# Temporary workaround to local graphviz rendering not running
quarkus.rest-client.graphviz-service.url=https://dapete.net/
quarkus.rest-client.graphviz-service.scope=jakarta.inject.Singleton
