---

name: Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # for Codecov
          fetch-depth: 2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven package
        run: ./mvnw -B package
      - uses: codecov/codecov-action@v5
      - uses: actions/upload-artifact@v4
        with:
          name: vcat-toolforge-runner
          path: vcat-toolforge-webapp/target/vcat-toolforge-runner.jar
