name: Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # for Codecov
        fetch-depth: 2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Maven package
      run: mvn -B package
    # TODO Codecov not working as of 2022-09-24, disable for now
    #- name: Trigger Codecov
    #  run: bash <(curl -s https://codecov.io/bash)
    - uses: actions/upload-artifact@v3
      with:
        name: vcat-toolforge
        path: vcat-toolforge-webapp/target/vcat-toolforge.war
